os:
- linux


language: python

# Travis tech support recommended trying sudo true for more stable builds.
# Seems odd, but maybe they isolate us from other users more if we need sudo.
sudo: false

python:
- 3.4
#- 3.5
#- 3.6
#- 3.7-dev

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        #- NUMPY_VERSION=1.13.1
        #- SCIPY_VERSION=0.19.1
        #- ASTROPY_VERSION=1.2.1
        #- CONFIGPARSER_VERSION=3.5.0
        #- HEALPY_VERSION=1.11.0
        #- MATPLOTLIB_VERSION=2.0.0
        # These packages will always be installed.
        #- CONDA_DEPENDENCIES="scipy pyyaml matplotlib healpy numpy configparser astropy"
        # These packages will only be installed if we really need them.
        #- CONDA_ALL_DEPENDENCIES=""
        # These packages will always be installed.
        #- PIP_DEPENDENCIES="scipy pyyaml matplotlib healpy numpy configparser astropy"
        # These packages will only be installed if we really need them.
        #- PIP_ALL_DEPENDENCIES=""
        # Debug the Travis install process.
        - DEBUG=True

install:
- pip install -r requirements.txt

deploy:
    provider: script
    script: cd examples; python mock_catalog_generation.py configs/RSD_mock.cfg
    on:
        branch: master
