os:
- linux
language: python
sudo: false
python:
- 3.5
- 3.6
- 3.7-dev
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- travis_wait 35 python setup.py install
script:
- generate_mock.py -c examples/configs/test.cfg -d 1 -a 1 -e 1 -u 0
after_success:
- bash push_new_version.sh
env:
  global:
    secure: aEJAPv8YP9ifVYE+iG7D2EwPDULgEpKDH2VdghhVtdqfx9baByi7A9ZgMaIVCrXETw3080DJxr44tzb3BYf8xtUvDdsbrpTCdxqqyqhH0EG2jAyb5mevahwJQ+XYFCCHtY0gAjj9NC8YvkumNIepk9J3jjSSk96r0H3UO8YY00QWQalVBAGVDPpy9LHjatYl3BWb8/4nCZDF4YE61XmbSUTk4Cs6Z6PTaQx9/BwsFttZsGtUZ3bhOBpNcbndIDa2A8hoQxVMLu1gzrg8M/NeT0YB5YOkWcXudqlZC6fY1jVkIkA37RgG3fhHBwDFH2Av/4bPEiO7MuujPJtolO3pPcdNBuYjuvUmZe+MLbg94kAUgFqK25YnMDacDho25ITCIKy5H1n4gVn4YFCeHHAhm1IGPUHqwLfqqWcwFqxOmUfmtGKjkeizJfCIaPBUTUmuWmakraS9gYaE6vL+95TtUHbFNvUEm+psxMg9Q309O9eItVyKnbwGgp8LswYysiIT0knuFQuzIMxSVT7MLEJrt+8s7Hu3wUYw1OPIn0Y/2M3LpifjFuIF4X7kcXQ1I6NtGhfKb6TkKQ0OSBHu52iZeE4ltxpHIjudxp+er6xb1UWOiTOTDCTVf1QqfkONkQMdy4RjT6m9q+mM7SYKeWm5nT6mLfnoVtOESOQjeKosPNE=
