os:
- linux
language: python
sudo: false
python:
- 3.5
- 3.6
- 3.7-dev
env:
  global:
  - DEBUG=True
  - secure: MoLub0GrpXVv3F3YVh0CBIvJGeipYzuiWGGWF5R+mBb4rrR1+TL8VMlHfa5fB9aHGa52Z3k71K5YnWFZw9p/abPau93wmxNzpgv74rSNhTlnWY5WLv7U1rvun4DAqIcnJqlndOMxEu/+85ziPEzFidXfmdjM0V2uKGG6SSlUXnG4xA0tUmLnvURnNsQa26KcL0LGSS7Q0JXxLn3x7Sn6AkmNjEzdDUaS7LxdD5Fc5pXECJiS6vS140sbt5zt/RO/wvFlyiCGw0oHcRY1yGBOMZdHjoENSQmvTaWNxJt7J/O0qYEHW73O0yiFIp3Q9gJTo5Mk8bO+gDpuRTumC+DEnXwNP16/90kOgeqWeewFHWRoufNb2YcanTPm9tz5wASuLVXmhjvn4PzFmDr8OXoqWJoye7TQTMATXBDWGl5diQOEVeE8UM40f4ghAXxg0HlP7yTta1dRegniit+MnCZFGFEJmdCROWNOb2XVaha/1d2QsKWB2fE6G6BWRZmhwb7zixP3QTqW07pREha8jAYTzCLlk5PyGBsPOHgEIn52IaDMj/cOOIJWWnD3aqcXR4gxfNqeYVNAFbSQRFiyvHTkAW4jCtUMsSouAKEFDIIx/ytAMhgRBLDzcLWJMEOCQrXOSTA0Db+61H0JJ68I+g4NnHCA2/h4C0YqihF/ilFuXFA=
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- travis_wait 30 python setup.py install
script:
- generate_mock.py -c examples/configs/test.cfg -d 1 -a 1 -e 1 -u 0
after_success:
- sh push_new_version.sh
