os:
- linux
language: python
sudo: false
python:
- 3.5
- 3.6
- 3.7-dev
env:
  global:
  - DEBUG=True
  - secure: jch/LqZ6K6uFnRw8EpdI6wdR+n/lKOCBfi4eJfUJZITYvY1B4vjNig+E5tXLOh3Xcd7b4m19Ig7oinP0/GJrWqw1XJ8T42UjIt5SbxpPne4nDaOyWQRcs4R4guuFlaCf8ghrjh+DOjAEY0olx5fLiWuj+FBfdK3A/trXLAvc+ZDsLttmTtkC5LWrD+E5xgSwsgW7A7LP2yLLbXyQoARSHy2rmw/56j29ths7k98CyPYiJ9DJY1WRscyWXWslFQj+YAmT6cbzTjC5l83hgeEefAOLtqy46/fWChapn03MNvkTKr9zRiAXhy/ruAHhu0aLUxKrHc7UMbh/yl/EhzdGkt4cFi2Z7nBZezZkKBgvpRXO7YQQyei08eFGNHRS6l/Jf/cwkYuJ2CNBsa2abdDAC7PEo1hAhChRsUln/7aWwVQmlE2w6L3O6NC+SII/UiqCqdmp8BlJbFjp/XBX+TQjopOkOvLLhXiLJyNAzZPkjxrs5tp5Q46seq2BSqT2dilRUN5GrpAK5RA7CUi2QKbkA8uTg3xn3nJ7JQsYNWd3FlspaP0wzJJOABfke5bpIqnpLq4u8vznQOyo01YLtKkotwem9PJkqq63TEfDlruP8IrDRoiMi9DLdgq2SlQ3XCSsY3auxLLkBsLnEBQi5gpUyFpdkBnwdLONFow+VifNivs=
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- travis_wait 30 python setup.py install
script:
- generate_mock.py -c examples/configs/test.cfg -d 1 -a 1 -e 1 -u 0
after_success:
- sh push_new_version.sh
