os:
- linux


language: python

# Travis tech support recommended trying sudo true for more stable builds.
# Seems odd, but maybe they isolate us from other users more if we need sudo.
sudo: false

# try for different python versions
python:
- 3.5
- 3.6
- 3.7-dev

env:
    global:
        - DEBUG=True

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- travis_wait 30 python setup.py install

script:
- generate_mock.py -c examples/configs/test.cfg -d 1 -a 1 -e 1 -u 0

after_success:
- python py/paramock/versioning.py
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git commit -m "after the successful build, updating the version number" py/paramock/_version.py
- git push --quiet origin development