os:
- linux


language: python

# Travis tech support recommended trying sudo true for more stable builds.
# Seems odd, but maybe they isolate us from other users more if we need sudo.
sudo: false

# try for different python versions
python:
- 3.4
#- 3.5
#- 3.6
#- 3.7-dev

env:
    global:
        - DEBUG=True

install:
- pip install -r requirements.txt

script: cd examples; python mock_catalog_generation.py configs/test.cfg
